services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: 
      - .env
    environment:
      - FLASK_ENV=production
      - REDIS_URL=${UPSTASH_REDIS_URL}
      - CELERY_BROKER_URL=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
      - CELERY_RESULT_BACKEND=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
    networks:
      - app-network

  celery-worker:
    build: .
    command: ["celery", "-A", "workers.tasks.celery", "worker", "--loglevel=info", "--concurrency=4", "--queues=ai_tasks,notifications,default"]
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
      - CELERY_RESULT_BACKEND=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
    networks:
      - app-network

  celery-beat:
    build: .
    command: ["celery", "-A", "workers.tasks.celery", "beat", "--loglevel=info", "--pidfile="]
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
      - CELERY_RESULT_BACKEND=${UPSTASH_REDIS_URL}/0?ssl_cert_reqs=required
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
