"""Remove task count column in categories table

Revision ID: 15f023034761
Revises: e99c246daa75
Create Date: 2025-03-29 08:59:29.876382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f023034761'
down_revision = 'e99c246daa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('tasks_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Optional counter for the number of tasks in this category'))

    # ### end Alembic commands ###
