"""modify mpesa otp column in payment detail model

Revision ID: 16a4baef3fcc
Revises: c38fa105d676
Create Date: 2025-04-16 15:01:00.431669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a4baef3fcc'
down_revision = 'c38fa105d676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_method', sa.String(length=50), nullable=True),
    sa.Column('mpesa_number', sa.String(length=20), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('name_holder', sa.String(length=100), nullable=True),
    sa.Column('cvc', sa.String(length=10), nullable=True),
    sa.Column('expirery', sa.String(length=10), nullable=True),
    sa.Column('mpesa_otp', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_details_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_details'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    # ### end Alembic commands ###
