"""drop platform_wallet table

Revision ID: 1f3ccc6453c3
Revises: cc5e1abb1078
Create Date: 2025-06-19 01:13:43.722066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f3ccc6453c3'
down_revision = 'cc5e1abb1078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_wallet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_wallet',
    sa.Column('balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
