"""Add sender_id to notifications

Revision ID: 24269b8ff723
Revises: aec72ece31ea
Create Date: 2025-05-31 23:25:02.504506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24269b8ff723'
down_revision = 'aec72ece31ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_sender_id_users'), 'users', ['sender_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_sender_id_users'), type_='foreignkey')
        batch_op.drop_column('is_important')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
