"""Add ondelete cascade to Message model foreign keys

Revision ID: 361db4ebcb52
Revises: e4cdc4f1b0b6
Create Date: 2025-04-15 15:44:06.953973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361db4ebcb52'
down_revision = 'e4cdc4f1b0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_reciever_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_message_sender_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_reciever_id_users'), 'users', ['reciever_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_message_sender_id_users'), 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_sender_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_reciever_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_message_sender_id_users', 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key('fk_message_reciever_id_users', 'users', ['reciever_id'], ['id'])

    # ### end Alembic commands ###
