"""Userinfo Update

Revision ID: 38afab5c15cc
Revises: 9cc9566d8982
Create Date: 2025-03-27 13:03:16.114083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38afab5c15cc'
down_revision = '9cc9566d8982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True, comment="User's short description"),
    sa.Column('bio', sa.Text(), nullable=True, comment="User's biography"),
    sa.Column('rating', sa.Float(), nullable=False, comment="User's rating (0.0 - 5.0)"),
    sa.Column('completion_rate', sa.Float(), nullable=False, comment='Task completion rate (0-100%)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_info_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_info'))
    )
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.create_index('idx_user_info_completion', ['completion_rate'], unique=False)
        batch_op.create_index('idx_user_info_rating', ['rating'], unique=False)
        batch_op.create_index('idx_user_info_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_info_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_info_user_id'))
        batch_op.drop_index('idx_user_info_user')
        batch_op.drop_index('idx_user_info_rating')
        batch_op.drop_index('idx_user_info_completion')

    op.drop_table('user_info')
    # ### end Alembic commands ###
