"""float wallet models

Revision ID: 3e26b9158d9f
Revises: d1a78c1b93ca
Create Date: 2025-06-11 20:28:49.969250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e26b9158d9f'
down_revision = 'd1a78c1b93ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], name=op.f('fk_wallet_transactions_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions'))
    )
    with op.batch_alter_table('platform_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
