"""Add columns to user table

Revision ID: 408f156df284
Revises: a4251aa474f8
Create Date: 2025-04-22 10:32:30.727545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408f156df284'
down_revision = 'a4251aa474f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_tasks_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_tasks_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cancelled_tasks_count')
        batch_op.drop_column('completed_tasks_count')

    # ### end Alembic commands ###
