"""add mpesa number to user_info model and encryption

Revision ID: 49ab21aa752c
Revises: 6ce06794dfdd
Create Date: 2025-04-15 01:29:52.259995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ab21aa752c'
down_revision = '6ce06794dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('mpesa_number')

    # ### end Alembic commands ###
