"""Create improved platform_wallet model with status, currency, and timestamps

Revision ID: 507f40a488d6
Revises: 1f3ccc6453c3
Create Date: 2025-06-19 01:15:45.017010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507f40a488d6'
down_revision = '1f3ccc6453c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('currency', sa.String(length=5), server_default='KES', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_wallet'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_wallet')
    # ### end Alembic commands ###
