"""update for push subscription valus

Revision ID: 54171bb679da
Revises: 8bab458f87fb
Create Date: 2025-06-05 22:02:37.194192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54171bb679da'
down_revision = '8bab458f87fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False, comment="Platform of the device (e.g., 'android', 'ios', 'web')"))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
