"""updates to wallet transactions added transaction fees to the model

Revision ID: 5b2c72d99756
Revises: 614ac4ee8120
Create Date: 2025-06-11 22:32:50.964506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2c72d99756'
down_revision = '614ac4ee8120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_fees', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('balance_after')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_after', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_fees')

    # ### end Alembic commands ###
