"""add currency column to paymentdetail model

Revision ID: 5e717ca8cab9
Revises: 16a4baef3fcc
Create Date: 2025-04-16 16:57:21.685117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e717ca8cab9'
down_revision = '16a4baef3fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
