"""edit usr_id to wallet transactions

Revision ID: 614ac4ee8120
Revises: 3e26b9158d9f
Create Date: 2025-06-11 22:27:06.767601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ac4ee8120'
down_revision = '3e26b9158d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_wallet_transactions_wallet_id_wallets', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_wallet_transactions_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_wallet_transactions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_wallet_transactions_wallet_id_wallets', 'wallets', ['wallet_id'], ['wallet_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
