"""Add bid relationship to task-assignment table

Revision ID: 6550a821b77f
Revises: 086eed16acf4
Create Date: 2025-04-01 22:56:20.693320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6550a821b77f'
down_revision = '086eed16acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bid_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_task_assignments_bid_id_bids'), 'bids', ['bid_id'], ['id'])
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Optional reference to a conversation for messaging'))
        batch_op.drop_constraint(batch_op.f('fk_task_assignments_bid_id_bids'), type_='foreignkey')
        batch_op.drop_column('bid_id')

    # ### end Alembic commands ###
