"""add collection ref column in wallet table

Revision ID: 67921cc138a3
Revises: c8bc67a00ac7
Create Date: 2025-04-21 18:33:30.906080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67921cc138a3'
down_revision = 'c8bc67a00ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eference', sa.String(length=255), nullable=True))
        batch_op.drop_column('reference')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_ref', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('collection_ref')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('eference')

    # ### end Alembic commands ###
