"""added task id to conversation resource 

Revision ID: 6c610520036e
Revises: 5b2c72d99756
Create Date: 2025-06-18 00:02:01.050594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c610520036e'
down_revision = '5b2c72d99756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_conversation_task_id_tasks'), 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversation_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
