"""Add statrt time and end time for preffered time

Revision ID: 6ecc10b8e52d
Revises: f7c426873af6
Create Date: 2025-04-03 15:50:12.290043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ecc10b8e52d'
down_revision = 'f7c426873af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_start_time', sa.Time(), nullable=True, comment="Start time if schedule_type is 'flexible'"))
        batch_op.add_column(sa.Column('preferred_end_time', sa.Time(), nullable=True, comment="End time if schedule_type is 'flexible'"))
        batch_op.drop_column('preferred_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_time', postgresql.TIME(), autoincrement=False, nullable=True, comment="Preferred time if schedule_type is 'flexible'"))
        batch_op.drop_column('preferred_end_time')
        batch_op.drop_column('preferred_start_time')

    # ### end Alembic commands ###
