"""Make is_deleted non-nullable

Revision ID: 704b0b58611f
Revises: ae02ee1b972f
Create Date: 2025-04-05 20:38:16.530343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704b0b58611f'
down_revision = 'ae02ee1b972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
