"""Changes

Revision ID: 7f151cf72d84
Revises: 2072e2bf03fa
Create Date: 2025-04-04 09:52:42.406751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f151cf72d84'
down_revision = '2072e2bf03fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_location_id_task_locations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_location_id_task_locations'), 'task_locations', ['location_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_location_id_task_locations'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_location_id_task_locations', 'task_locations', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
