"""changes

Revision ID: 7fc43d546977
Revises: 24269b8ff723
Create Date: 2025-06-02 13:17:40.322399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fc43d546977'
down_revision = '24269b8ff723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_sender_id_users', type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_time', sa.Time(), nullable=True, comment="Time if schedule_type is 'flexible'"))
        batch_op.drop_column('preferred_start_time')
        batch_op.drop_column('preferred_end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_end_time', postgresql.TIME(), autoincrement=False, nullable=True, comment="End time if schedule_type is 'flexible'"))
        batch_op.add_column(sa.Column('preferred_start_time', postgresql.TIME(), autoincrement=False, nullable=True, comment="Start time if schedule_type is 'flexible'"))
        batch_op.drop_column('preferred_time')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_notifications_sender_id_users', 'users', ['sender_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
