"""Change unique constraint in the name column on the users table

Revision ID: 875566ef1502
Revises: 38afab5c15cc
Create Date: 2025-03-27 13:31:15.220248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875566ef1502'
down_revision = '38afab5c15cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_name')
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.create_index('ix_users_name', ['name'], unique=True)

    # ### end Alembic commands ###
