"""fix city value

Revision ID: 8b6ee001cf83
Revises: 6ae1f2ef23d8
Create Date: 2025-08-10 00:38:22.075248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6ee001cf83'
down_revision = '6ae1f2ef23d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
