"""add image to messag model

Revision ID: 8bab458f87fb
Revises: cae409468499
Create Date: 2025-06-04 17:07:50.874124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bab458f87fb'
down_revision = 'cae409468499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
