"""Add a auth_provider column to the user table

Revision ID: 9a5a52338c5f
Revises: 875566ef1502
Create Date: 2025-03-27 17:50:57.765397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5a52338c5f'
down_revision = '875566ef1502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), server_default='email', nullable=False, comment="Authentication provider; defaults to 'email' for email/password login"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
