"""add disbursment_ref to walllet table

Revision ID: a4251aa474f8
Revises: 67921cc138a3
Create Date: 2025-04-21 21:29:52.348858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4251aa474f8'
down_revision = '67921cc138a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disbursment_ref', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('disbursment_ref')

    # ### end Alembic commands ###
