"""Changes

Revision ID: a900b4c0eea3
Revises: 7f151cf72d84
Create Date: 2025-04-04 10:01:18.695851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a900b4c0eea3'
down_revision = '7f151cf72d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False, comment='Associated task'))
        batch_op.create_unique_constraint(batch_op.f('uq_task_locations_task_id'), ['task_id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_locations_task_id_tasks'), 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_location_id_task_locations', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Required if work_mode is physical'))
        batch_op.create_foreign_key('fk_tasks_location_id_task_locations', 'task_locations', ['location_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_locations_task_id_tasks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_task_locations_task_id'), type_='unique')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
