"""add balance to floatwallet

Revision ID: aec72ece31ea
Revises: 3b58269e4ee9
Create Date: 2025-05-21 01:11:27.499886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec72ece31ea'
down_revision = '3b58269e4ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('float_wallet_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False))

    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))

    with op.batch_alter_table('float_wallet_ledger', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
