"""create conversation and message models

Revision ID: b0a9d3dab99c
Revises: 7c97268372e3
Create Date: 2025-04-03 14:19:43.862979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a9d3dab99c'
down_revision = '7c97268372e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_giver', sa.Integer(), nullable=False),
    sa.Column('task_doer', sa.Integer(), nullable=False),
    sa.Column('last_msg_id_giver', sa.Integer(), nullable=True),
    sa.Column('last_msg_id_doer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_doer'], ['users.id'], name=op.f('fk_conversation_task_doer_users')),
    sa.ForeignKeyConstraint(['task_giver'], ['users.id'], name=op.f('fk_conversation_task_giver_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('task_giver', sa.Integer(), nullable=False),
    sa.Column('task_doer', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation')),
    sa.ForeignKeyConstraint(['task_doer'], ['users.id'], name=op.f('fk_message_task_doer_users')),
    sa.ForeignKeyConstraint(['task_giver'], ['users.id'], name=op.f('fk_message_task_giver_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
