"""Remove completion rate and reviews column from the userinfo table

Revision ID: b1058ed0ec77
Revises: 1d432690b0c9
Create Date: 2025-04-01 23:16:18.655893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1058ed0ec77'
down_revision = '1d432690b0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index('idx_user_info_completion')
        batch_op.drop_index('idx_user_info_rating')
        batch_op.drop_column('rating')
        batch_op.drop_column('completion_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Task completion rate (0-100%)'))
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment="User's rating (0.0 - 5.0)"))
        batch_op.create_index('idx_user_info_rating', ['rating'], unique=False)
        batch_op.create_index('idx_user_info_completion', ['completion_rate'], unique=False)

    # ### end Alembic commands ###
