"""changes

Revision ID: b2290555cc4e
Revises: 7fc43d546977
Create Date: 2025-06-03 15:22:55.888517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2290555cc4e'
down_revision = '7fc43d546977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
