"""changes

Revision ID: b2bd0eeea4b9
Revises: 6ce06794dfdd
Create Date: 2025-04-15 15:22:16.665811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bd0eeea4b9'
down_revision = '6ce06794dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('mpesa_number')

    with op.batch_alter_table('user_relations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_relations_related_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_user_relations_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_relations_related_user_id_users'), 'users', ['related_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_relations_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_relations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_relations_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_relations_related_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_relations_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_user_relations_related_user_id_users', 'users', ['related_user_id'], ['id'])

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
