"""fix rating column

Revision ID: bacd6a6cde61
Revises: 49ab21aa752c
Create Date: 2025-04-15 02:18:19.701009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacd6a6cde61'
down_revision = '49ab21aa752c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
