"""Changes

Revision ID: c05031a45849
Revises: 4b6c86c93668
Create Date: 2025-04-03 09:58:47.083137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05031a45849'
down_revision = '4b6c86c93668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.drop_index('idx_task_locations_city')
        batch_op.drop_index('idx_task_locations_coords')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_budget')
        batch_op.drop_index('idx_tasks_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_budget', ['budget'], unique=False)

    with op.batch_alter_table('task_locations', schema=None) as batch_op:
        batch_op.create_index('idx_task_locations_coords', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_task_locations_city', [sa.literal_column('lower(city::text)')], unique=False)

    # ### end Alembic commands ###
