"""add payment details models

Revision ID: c38fa105d676
Revises: e91c6962a452
Create Date: 2025-04-16 14:37:26.737972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38fa105d676'
down_revision = 'e91c6962a452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_reviewee_id', ['reviewee_id'], unique=False)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('mpesa_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_reviewee_id')

    # ### end Alembic commands ###
