"""Add cascade delete to conversation foreign keys

Revision ID: c4c5c6fad70a
Revises: e4ec1cd72eef
Create Date: 2025-04-15 15:28:51.753885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c5c6fad70a'
down_revision = 'e4ec1cd72eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_task_giver_users', type_='foreignkey')
        batch_op.drop_constraint('fk_conversation_task_doer_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_task_doer_users'), 'users', ['task_doer'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_task_giver_users'), 'users', ['task_giver'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversation_task_giver_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conversation_task_doer_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_conversation_task_doer_users', 'users', ['task_doer'], ['id'])
        batch_op.create_foreign_key('fk_conversation_task_giver_users', 'users', ['task_giver'], ['id'])

    # ### end Alembic commands ###
