"""update card details to card_token

Revision ID: c8bc67a00ac7
Revises: 5e717ca8cab9
Create Date: 2025-04-17 16:06:42.072738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bc67a00ac7'
down_revision = '5e717ca8cab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_token', sa.String(length=255), nullable=True))
        batch_op.drop_column('expirery')
        batch_op.drop_column('name_holder')
        batch_op.drop_column('card_number')
        batch_op.drop_column('cvc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvc', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name_holder', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expirery', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('card_token')

    # ### end Alembic commands ###
