"""changes

Revision ID: cae409468499
Revises: b2290555cc4e
Create Date: 2025-06-04 11:41:31.908479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cae409468499'
down_revision = 'b2290555cc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('preferred_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_comment="Time if schedule_type is 'flexible'",
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('preferred_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_comment="Time if schedule_type is 'flexible'",
               existing_nullable=True)

    # ### end Alembic commands ###
