"""fix platfrom wallet

Revision ID: cc5e1abb1078
Revises: 8323eea83fb0
Create Date: 2025-06-19 01:07:16.162022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5e1abb1078'
down_revision = '8323eea83fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###
