"""changes

Revision ID: d1a78c1b93ca
Revises: 54171bb679da
Create Date: 2025-06-06 11:50:02.348917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a78c1b93ca'
down_revision = '54171bb679da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True, comment="Rating of the user's rating"))
        batch_op.add_column(sa.Column('completion_rate', sa.Float(), nullable=True, comment="Completion rating of the user's rating"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('completion_rate')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
