"""add messages.status andi its default value

Revision ID: dfd284298ab5
Revises: 6ecc10b8e52d
Create Date: 2025-04-03 18:25:47.286850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd284298ab5'
down_revision = '6ecc10b8e52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
