"""Add ondelete cascade to review foreign keys

Revision ID: e4cdc4f1b0b6
Revises: c4c5c6fad70a
Create Date: 2025-04-15 15:35:56.995625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cdc4f1b0b6'
down_revision = 'c4c5c6fad70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_reviewee_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_reviewer_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_task_assignment_id_task_assignments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_reviewee_id_users'), 'users', ['reviewee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_reviewer_id_users'), 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_task_assignment_id_task_assignments'), 'task_assignments', ['task_assignment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_task_assignment_id_task_assignments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_reviewer_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_reviewee_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_task_assignment_id_task_assignments', 'task_assignments', ['task_assignment_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_reviewer_id_users', 'users', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_reviewee_id_users', 'users', ['reviewee_id'], ['id'])

    # ### end Alembic commands ###
