"""changes

Revision ID: e4ec1cd72eef
Revises: b2bd0eeea4b9
Create Date: 2025-04-15 15:25:42.741014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ec1cd72eef'
down_revision = 'b2bd0eeea4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_notifications_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
