"""add user relation model

Revision ID: f499585c5be5
Revises: 704b0b58611f
Create Date: 2025-04-09 20:37:31.748321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f499585c5be5'
down_revision = '704b0b58611f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], name=op.f('fk_user_relations_related_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_relations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_relations'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_tasks_is_deleted', ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_is_deleted')
        batch_op.drop_index('ix_tasks_deleted_at')

    op.drop_table('user_relations')
    # ### end Alembic commands ###
