"""updated message models cononstrains

Revision ID: f7c426873af6
Revises: b0a9d3dab99c
Create Date: 2025-04-03 15:31:42.734080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c426873af6'
down_revision = 'b0a9d3dab99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reciever_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_message_task_doer_users', type_='foreignkey')
        batch_op.drop_constraint('fk_message_task_giver_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_reciever_id_users'), 'users', ['reciever_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_message_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.drop_column('task_giver')
        batch_op.drop_column('task_doer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_doer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('task_giver', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_message_sender_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_reciever_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_message_task_giver_users', 'users', ['task_giver'], ['id'])
        batch_op.create_foreign_key('fk_message_task_doer_users', 'users', ['task_doer'], ['id'])
        batch_op.drop_column('reciever_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
